### ISSUE TITLE
UE5 Import Scripts Broken

### ISSUE THREAD

**Issue by Edragyz** [MontagueM/Charm#106]
Still 100% a noob with this stuff so this may be user error? Myself and a few other users that have managed to get UE5 imports to work flawlessly in the past, haven't been able to get the latest version to work. Objects are being imported with no textures, some objects don't get imported at all, and after the import finishes we're met with a new error message that we hadn't seen prior to this version of Charm.

Error: FBX Scene Loading: Found material name clash. name clash can be wrongly reassign at reimport . material (name here) was renamed (new name here)

This error occurs on every import we've tried.

**Comment by JustOrbs** [comment]
bumb

**Comment by Edragyz** [comment]
Issue is ongoing in Charm 2.0. Something in the Python script isn't working properly. Textures are present in the texture folder but aren't being applied during import.

**Comment by tgrafk12** [comment]
bump.
really wanted to get the Black Garden imported to Unity, but im not seeing any of the textures map over to the materials at all, and it looks like id have to do that manually. (Which im not familiar with Unreal Engine at all, so thats a HUGE issue to me) :<
Really hope it gets fixed soon, cause i REALLY wanna see how crazy some of these maps are in VR. *not optimized at all with over 1m tris, but eh whatever*

**Comment by nblockbuster** [comment]
This issue is still present on b638549dbf3d36af2a565e9f07dc2bf78c0e1e45.
```
LogEditorAssetSubsystem: Error: DoesDirectoryExist failed: Could not convert path: Can't convert the path 'Content' because it does not map to a root.
LogEditorAssetSubsystem: Error: MakeDirectory failed: Could not convert the path. Content
LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "G:/charm2_exports/Maps/The Anomaly/85F4AA80_import_to_ue5.py", line 365, in <module>
LogPython: Error:     importer.import_map()
LogPython: Error:   File "G:/charm2_exports/Maps/The Anomaly/85F4AA80_import_to_ue5.py", line 34, in import_map
LogPython: Error:     self.assemble_map()
LogPython: Error:   File "G:/charm2_exports/Maps/The Anomaly/85F4AA80_import_to_ue5.py", line 56, in assemble_map
LogPython: Error:     for part in parts:
LogPython: Error:                 ^^^^^
LogPython: Error: UnboundLocalError: cannot access local variable 'parts' where it is not associated with a value
```
Every material is blank, showing only a node of constant value 0 plugged into the opacity mask, and no textures imported into the materials.
